# Generated by Django 2.2.5 on 2019-10-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
